apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-demo
resources:
  - ../../base
  - nginx.yaml
patchesStrategicMerge:
  - whoami.yaml
configMapGenerator:
  - name: example-config
    files:
      - sample.env
