apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-demo
resources:
  - resources.yaml
  - ../aws
patchesStrategicMerge:
  - whoami.yaml

replacements:
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.hostname
    targets:
      - select:
          namespace: whoami-demo
          name: ingress-whoami
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
configMapGenerator:
  - name: example-config
    behavior: merge
    env: updates.env
