{{- if .Values.mariadbVolumeId }}
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb

---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb
      ports:
        - containerPort: 3306
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: "password"
        - name: "MARIADB_DATABASE"
          value: "database"
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume
  volumes:
    - name: data-volume
      # This AWS EBS volume must already exist.
      awsElasticBlockStore:
        volumeID: {{ .Values.mariadbVolumeId }}
        fsType: ext4
  tolerations:
  - key: "aws"
    operator: "Equal"
    value: "ec2"
    effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
{{ end -}}