---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoamiapp
  template:
    metadata:
      labels:
        app: whoamiapp
    spec:
      containers:
        - name: whatsthis
          image: containous/whoami
          env:
            - name: GET_HOSTS_FROM
              value: "dns"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami-demo
  labels:
    app: whoami-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: whoamiapp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whoami-demo
  name: ingress-whoami
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

{{- if .Values.dnsHostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsHostname | quote }}
{{- end }}

{{- /*
Expose port 443 as well as port 80 if at least one HTTPS host is set
(this host is used for the certificate selection by the ALB)
*/}}
{{- if .Values.tlsHosts }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
{{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
{{- end }}

spec:
{{- if .Values.tlsHosts }}
  tls:
    - hosts:
      {{- range .Values.tlsHosts }}
      - {{ . | quote }}
      {{- end -}}
{{- end }}
  rules:
    - http:
        paths:
          - path: /whoami
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
