apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami-demo
resources:
  - ../dns
patchesStrategicMerge:
  - whoami.yaml

replacements:
  - source:
      kind: ConfigMap
      name: kustomize-config
      fieldPath: data.hostname
    targets:
      - select:
          namespace: whoami-demo
          name: ingress-whoami
        fieldPaths:
          - spec.tls.0.hosts.0
configMapGenerator:
  - name: example-config
    behavior: merge
    env: updates.env
